---
title: "Client Report - Can You Predict That?"
subtitle: "Unit 4 Task 1"
author: "John Zhou"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn import metrics
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)

```


```{python}
# import your data here using polars and the URL
df = pl.read_csv("dwellings_ml.csv")

```

## QUESTION

1. __Take time to get to know your data.__ Based on some initial exploration, identify 3 variables in the dataset you think will have strong predictive ability for determining if a house was built before 1980. Explain/justify the reasoning behind your guesses (for example with plots).

_I guess that the variables nocars, livearea, and stories have strong predictive ability because I think that nocars, which means the size of the garage for car number, is correlated to the build year because the house that was built could have a smaller or even no garage for cars. And I think that the houses that were built more recently could have a bigger living area and maybe multiple stories._

```{python}
# Optional: code you used to get to know your data


```

1. __Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Report your final model choice and any other model parameters you may have tweaked (train-test split ratio, tuning parameters, etc).  

_I have tried the decision tree classifier and the random forest classifier, and I found that the random forest classifier can provide better results. I also set the number of estimators for random forest to 200 and eventually achieved 93% accuracy._

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

df_clean = (
  df.drop(["yrbuilt", "parcel"])
)

x = df_clean.drop("before1980")
y = df_clean.select("before1980")

x_train, x_test, y_train, y_test = train_test_split(
  x, y,
  test_size=0.2,
  random_state=42
)

decision_tree = DecisionTreeClassifier(
  random_state=42
)

random_forest = RandomForestClassifier(
  n_estimators=200,
  random_state=42
)

random_forest.fit(x_train, y_train)

pred = random_forest.predict(x_test)

print(classification_report(y_test, pred))
```

