---
title: "Client Report - Baseball Database SQL Query"
subtitle: "Unit 3 Task 2"
author: "John Zhou"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

_According to the output, we can see that the top 5 results are all 100%, and the player ID was ordered alphabetically, starting with "a." It is probably because the player just did one or two hits, and they succeeded in that year._

```{python}
# Include and execute your code here

# The code below can serve as a template for all the rest of your queries. It is just missing the SQL code. Put your SQL query in between the triple quotation marks to create the query. The records will be stored in 'results', which is a polars data frame

q = """
        SELECT   playerID
               , yearID
               , ROUND(100.0 * SUM(H) / SUM(AB), 2) AS batting_percentage
        FROM     batting
        GROUP BY playerID, yearID
        HAVING   SUM(AB) >= 1
        ORDER BY batting_percentage DESC
               , playerID ASC
        LIMIT    5
    """
results = pl.read_database(q, con, infer_schema_length=10000)
results
```


## QUESTION 2

__Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.__  

_With at-bats greater than or equal to 10, we can see that we got more meaningful results, and the top 5 player IDs that have the most batting averages are nymanny01 with 64.29%, carsoma01 with 63.64%, altizda01 with 60%, silvech01 with 57.14%, and puccige01 with 56.25%._

```{python}
# Include and execute your code here
q = """
        SELECT   playerID
               , yearID
               , ROUND(100.0 * SUM(H) / SUM(AB), 2) AS batting_percentage
        FROM     batting
        GROUP BY playerID, yearID
        HAVING   SUM(AB) >= 10
        ORDER BY batting_percentage DESC
               , playerID ASC
        LIMIT    5
    """
results = pl.read_database(q, con, infer_schema_length=10000)
results

```


## QUESTION 3

__Now modify the SQL query to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

_According to the result, we can see that the top 5 player IDs that have the most batting averages in their entire careers with at-bats of at least 100 are cobbty01 with 36.63%, barnero01 with 35.97%, hornsro01 with 35.85%, jacksjo01 with 35.58%, and meyerle01 with 35.55%._

```{python}
# Include and execute your code here
q = """
        SELECT   playerID
               , ROUND(100.0 * SUM(H) / SUM(AB), 2) AS batting_percentage
        FROM     batting
        GROUP BY playerID
        HAVING   SUM(AB) >= 100
        ORDER BY batting_percentage DESC
               , playerID ASC
        LIMIT    5
    """
results = pl.read_database(q, con, infer_schema_length=10000)
results

```